# -*- coding: utf-8 -*-
"""E-Business-CollectingData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnqUMDR8UDDt0_Rwh67whaauxfhhXNb2
"""

!pip install --upgrade together

import re
import unicodedata
import requests
from bs4 import BeautifulSoup
import csv
from together import Together
client = Together(api_key='0e22219e5d412fb12ae4c4a3fd7e611210834b75703de2697c6640179554583a')

def crawl_and_return_content(url):
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        # Lấy nội dung trong div chính
        target_div = soup.find('div', {'id': 'content', 'class': 'mc-content span9'})
        if not target_div:
            print("[Error] - Không tìm thấy div với id='content' và class='mc-content span9'")
            return

        # Lấy text trong div
        text_content = target_div.get_text(separator='\n', strip=True)

        # return text
        return text_content
    except Exception as e:
        print(f"[Error] - crawl_and_return_content - Đã xảy ra lỗi: {e}")

def defined_prompt_summary(text):
  try:
    promt_temp = """
      Bạn là một trợ lý thông minh, có khả năng đọc hiểu nội dung từ một đoạn thông tin được cung cấp. bạn cần thực hiện các bước sau:
      1. Truy cập vào đường link và đọc toàn bộ nội dung của trang.
      2. Trích xuất và liệt kê lại **20 điểm chính** quan trọng nhất, chú ý đến:
        - Các con số cụ thể (ví dụ: chỉ tiêu, lệ phí, mã ngành,...)
        - Mốc thời gian quan trọng (ví dụ: hạn nộp, ngày thi, ngày khai giảng,...)
        - Địa điểm, hình thức học, liên hệ...
        - Cách đăng ký, hình thức xét tuyển, điều kiện miễn thi,...
        - Và các chủ thể quan trọng khác như lịch học, thời khoá biểu, các ngày diễn ra sự kiện...
      3. Đảm bảo thông tin được trình bày rõ ràng, ngắn gọn, có đánh số thứ tự.
      4. Giữ nguyên tên riêng, mã ngành, địa chỉ, đường link nếu có.
      5. Không đưa ra ý kiến chủ quan hay suy đoán, chỉ tóm tắt chính xác nội dung.
      6. Lưu ý, nếu nội dung nào không rõ hay không thể tổng hợp thông tin thì hãy loại bỏ nó ra khỏi danh sách 20 điểm tóm tắt.
      Bạn sẽ trả lời như sau:
      [ghi rõ 20 điểm tóm tắt giống như mẫu ChatGPT đã cung cấp theo cú pháp <stt>. <title>:<content> ]
      ==> Đây là đầu vào mẫu để bạn học theo. Hãy luôn làm theo định dạng này khi được yêu cầu tóm tắt một bài viết từ đoạn thông tin: {}
      """
    return promt_temp.format(text)
  except Exception as e:
    print(f"[Error] - defined_prompt_summary - Đã xảy ra lỗi: {e}")

def response_ai(prompt):
  try:
    # question = input("tell me your question...")
    response = client.chat.completions.create(
        # model="meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
        model="meta-llama/Llama-Vision-Free",
        # model="deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )
    return response.choices[0].message.content
  except Exception as e:
        print(f"[Error] - response_ai - Đã xảy ra lỗi: {e}")

def nlu_extract_questions(text):
    matches = re.findall(r"Câu Hỏi Là:\s*(.+?)(?:\?|\.|!|\n)", text)
    return [q.strip() + "?" for q in matches]

def nlu_create_question_from_text(obj_text, title_notification):
  try:
    prompt = """
    Hãy giúp tôi tạo ra 5 câu hỏi mà người dùng có thể hỏi được suy luận từ 2 đoạn text này {} và tiêu đề thông báo là {}
    Lưu ý: trả lời ngắn gọn, đưa ra câu hỏi không cần đưa ra đáp án, không rườm rà và thêm các thông tin khác, trả theo cú pháp "Câu Hỏi Là:... ?"
    """.format(obj_text['title'], title_notification)
    response = response_ai(prompt)
    return nlu_extract_questions(response)
  except Exception as e:
        print(f"[Error] - nlu_create_question_from_text - Đã xảy ra lỗi: {e}")

# Hàm lấy title của bài viết
def get_title_notification(text):
    lines = text.strip().splitlines()[:3]
    noti = "THÔNG BÁO"
    for line in lines:
        if (noti.upper())in line.upper():
            return line.strip()
    return ""
def extract_questions_(text):
    matches = re.findall(r"Câu Hỏi Là:\s*(.+?)(?:\?|\.|!|\n)", text)
    return [q.strip() + "?" for q in matches]
#---------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------
# Hàm loại bỏ dấu tiếng Việt
def strip_accents(text):
    nfkd = unicodedata.normalize('NFKD', text)
    return ''.join([c for c in nfkd if not unicodedata.combining(c)])

# Tạo code từ title
def generate_code(title):
    return re.sub(r'\s+', '_', strip_accents(title.lower()))

# Danh sách cần loại bỏ nếu content chứa các từ khóa này (sau khi bỏ dấu)
list_key_ignore_raw = ["không rõ", "khong ro", "không có thông tin", "Không rõ."]
list_key_ignore = [strip_accents(x.lower()) for x in list_key_ignore_raw]

# Hàm lọc đi các từ khoá trong danh sách ignore
def filter_objects(array, ignore_list):
    ignore_list_lower = [s.lower() for s in ignore_list]
    result = [
        obj for obj in array
        if all(ignore not in obj['content'].lower() for ignore in ignore_list_lower)
    ]
    return result

# Tách từng mục trong văn bản và trả về danh sách dict
def create_list_dictionary(text):
    try:
        pattern = r'\d+\.\s+\*\*(.+?)\*\*:\s*(.*?)(?=\n\d+\.|\Z)'
        matches = re.findall(pattern, text, re.DOTALL)
        result = [
            {
                "title": title.strip(),
                "code": generate_code(title.strip()),
                "content": content.strip()
            }
            for title, content in matches
            #if not is_ignored(content)
        ]
        # return filter_objects(result, list_key_ignore)
        return result
    except Exception as e:
        print(f"[Error] - create_list_dictionary - Đã xảy ra lỗi: {e}")
        return []

#I. COLLECT - SUMMARY
#I. 1 Crawling
input_url = input("Nhập Url: ")
data_crawled = crawl_and_return_content(input_url)
title_notification = get_title_notification(data_crawled)
#I. 2 Summary
summary_prompt = defined_prompt_summary(data_crawled);
#I. 3 Create Summary Data
data_final_summary = response_ai(summary_prompt);

print(data_final_summary)

# #II. Data into File
# print("--------------------------------------------- nlu.yml");
# nlu_list_dictionary = create_list_dictionary(data_final_summary);
# # i = 0
# for i in nlu_list_dictionary:
#   nlu_intent = generate_code(title_notification)
#   nlu_list_question  = nlu_create_question_from_text(nlu_list_dictionary[0], title_notification);
#   nlu_examples = "\n\n".join(f"- {q}" for q in nlu_list_question)
#   print(nlu_examples)